#!/usr/bin/env python3
"""
import_flows.py
----------------
Pushes a locally-edited flow JSON file (from /connect-flows) back up to
an Amazon Connect instance, updating the flow's content in place.

This updates an EXISTING flow's content -- it does not create new flows.
Create new flows in the Connect console first (so they get a ContactFlowId),
export once with export_flows.py, then use this script for subsequent
updates.

Usage:
    python scripts/import_flows.py --instance-id <INSTANCE_ID> --file connect-flows/main-menu.json

    # Preview what would be sent, without actually updating Connect
    python scripts/import_flows.py --instance-id <INSTANCE_ID> --file connect-flows/main-menu.json --dry-run

Requires:
    pip install boto3
    AWS credentials configured (aws configure / env vars / SSO)
    IAM permissions: connect:UpdateContactFlowContent, connect:DescribeContactFlow
"""

import argparse
import json
import sys

import boto3
from botocore.exceptions import ClientError


def load_flow_file(filepath: str) -> dict:
    with open(filepath) as f:
        data = json.load(f)

    for required_key in ("ContactFlowId", "Content"):
        if required_key not in data:
            print(
                f"Error: '{filepath}' is missing required key '{required_key}'. "
                "Was this file generated by export_flows.py?",
                file=sys.stderr,
            )
            sys.exit(1)

    return data


def import_flow(client, instance_id: str, flow_data: dict, dry_run: bool = False):
    contact_flow_id = flow_data["ContactFlowId"]
    content_str = json.dumps(flow_data["Content"])

    if dry_run:
        print(f"[dry-run] Would update flow '{flow_data.get('Name', contact_flow_id)}' "
              f"(ContactFlowId={contact_flow_id})")
        print(f"[dry-run] Content payload size: {len(content_str)} bytes")
        return

    try:
        client.update_contact_flow_content(
            InstanceId=instance_id,
            ContactFlowId=contact_flow_id,
            Content=content_str,
        )
    except ClientError as e:
        print(f"Error updating flow: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Updated flow '{flow_data.get('Name', contact_flow_id)}' "
          f"(ContactFlowId={contact_flow_id}) in Connect instance {instance_id}")


def main():
    parser = argparse.ArgumentParser(description="Import a local flow JSON file into Amazon Connect")
    parser.add_argument("--instance-id", required=True, help="Amazon Connect instance ID")
    parser.add_argument("--file", required=True, help="Path to the flow JSON file (e.g. connect-flows/main-menu.json)")
    parser.add_argument("--region", default=None, help="AWS region (defaults to your configured region)")
    parser.add_argument("--dry-run", action="store_true", help="Print what would happen without calling the API")
    args = parser.parse_args()

    flow_data = load_flow_file(args.file)
    client = boto3.client("connect", region_name=args.region)

    import_flow(client, args.instance_id, flow_data, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
